// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeUrYf-3BfZaINhQaSlqf_W39LDVJK48k',
    appId: '1:1063946903752:web:a58ddbd1b5e13b7d6f05fd',
    messagingSenderId: '1063946903752',
    projectId: 'healthtrack-30662',
    authDomain: 'healthtrack-30662.firebaseapp.com',
    databaseURL: 'https://healthtrack-30662-default-rtdb.firebaseio.com',
    storageBucket: 'healthtrack-30662.appspot.com',
    measurementId: 'G-G452FEZY8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlaPqM2N4oNCBScngMJpNsW1BnF4KipkA',
    appId: '1:1063946903752:android:8fefcea2287ce2b06f05fd',
    messagingSenderId: '1063946903752',
    projectId: 'healthtrack-30662',
    databaseURL: 'https://healthtrack-30662-default-rtdb.firebaseio.com',
    storageBucket: 'healthtrack-30662.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1V5GR71qEX3h0VKsjD_BNfaNZZfqZ6yI',
    appId: '1:1063946903752:ios:69b3ac2a5582c68f6f05fd',
    messagingSenderId: '1063946903752',
    projectId: 'healthtrack-30662',
    databaseURL: 'https://healthtrack-30662-default-rtdb.firebaseio.com',
    storageBucket: 'healthtrack-30662.appspot.com',
    iosClientId: '1063946903752-1vtomlok9uq4v7kn6ul2s82ci8noaut5.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthtrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1V5GR71qEX3h0VKsjD_BNfaNZZfqZ6yI',
    appId: '1:1063946903752:ios:121f360b509c55a96f05fd',
    messagingSenderId: '1063946903752',
    projectId: 'healthtrack-30662',
    databaseURL: 'https://healthtrack-30662-default-rtdb.firebaseio.com',
    storageBucket: 'healthtrack-30662.appspot.com',
    iosClientId: '1063946903752-q841kr30uri74o413fufb4lc3if65g6r.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthtrack.RunnerTests',
  );
}
